added first working serial interface

diff --git a/flash b/flash
--- a/flash
+++ b/flash
@@ -2,9 +2,12 @@ INPUT_FILE_ELIF="target/thumbv7m-none-eabi/release/midi_clock"
 OUTPUT_FILE_BIN="target/midi_clock.bin"
 FLASH_ADDRESS="0x08000000"
 
+set -e # stop on error
+
 echo "Compiling program..."
 cargo build --release
 echo "Copying elif to bin."
+rm $OUTPUT_FILE_BIN
 arm-none-eabi-objcopy -O binary $INPUT_FILE_ELIF $OUTPUT_FILE_BIN
 echo "Writing programm to chip..."
 st-flash write $OUTPUT_FILE_BIN $FLASH_ADDRESS
